apiVersion: v1
kind: Service
metadata:
  labels:
    app: argocd-server
  name: argocd-loadbalancer
  namespace: argocd
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080

  selector:

    app.kubernetes.io/name: argocd-server
  type: LoadBalancer
