apiVersion: v1
kind: Service
metadata:
  labels:
    app: argocd
  name: argocd-loadbalancer
  namespace: default
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080

  selector:
    app.kubernetes.io/instance: argo-cd
    app.kubernetes.io/name: argocd-server
  type: LoadBalancer
